const departments = [
    { label: "Ain", code: "01" },
    { label: "Aisne", code: "02" },
    { label: "Allier", code: "03" },
    { label: "Alpes-de-Haute-Provence", code: "04" },
    { label: "Hautes-Alpes", code: "05" },
    { label: "Alpes-Maritimes", code: "06" },
    { label: "Ardèche", code: "07" },
    { label: "Ardennes", code: "08" },
    { label: "Ariège", code: "09" },
    { label: "Aube", code: "10" },
    { label: "Aude", code: "11" },
    { label: "Aveyron", code: "12" },
    { label: "Bouches-du-Rhône", code: "13" },
    { label: "Calvados", code: "14" },
    { label: "Cantal", code: "15" },
    { label: "Charente", code: "16" },
    { label: "Charente-Maritime", code: "17" },
    { label: "Cher", code: "18" },
    { label: "Corrèze", code: "19" },
    { label: "Corse-du-Sud", code: "2A" },
    { label: "Haute-Corse", code: "2B" },
    { label: "Côte-d’Or", code: "21" },
    { label: "Côtes-d’Armor", code: "22" },
    { label: "Creuse", code: "23" },
    { label: "Dordogne", code: "24" },
    { label: "Doubs", code: "25" },
    { label: "Drôme", code: "26" },
    { label: "Eure", code: "27" },
    { label: "Eure-et-Loir", code: "28" },
    { label: "Finistère", code: "29" },
    { label: "Gard", code: "30" },
    { label: "Haute-Garonne", code: "31" },
    { label: "Gers", code: "32" },
    { label: "Gironde", code: "33" },
    { label: "Hérault", code: "34" },
    { label: "Ille-et-Vilaine", code: "35" },
    { label: "Indre", code: "36" },
    { label: "Indre-et-Loire", code: "37" },
    { label: "Isère", code: "38" },
    { label: "Jura", code: "39" },
    { label: "Landes", code: "40" },
    { label: "Loir-et-Cher", code: "41" },
    { label: "Loire", code: "42" },
    { label: "Haute-Loire", code: "43" },
    { label: "Loire-Atlantique", code: "44" },
    { label: "Loiret", code: "45" },
    { label: "Lot", code: "46" },
    { label: "Lot-et-Garonne", code: "47" },
    { label: "Lozère", code: "48" },
    { label: "Maine-et-Loire", code: "49" },
    { label: "Manche", code: "50" },
    { label: "Marne", code: "51" },
    { label: "Haute-Marne", code: "52" },
    { label: "Mayenne", code: "53" },
    { label: "Meurthe-et-Moselle", code: "54" },
    { label: "Meuse", code: "55" },
    { label: "Morbihan", code: "56" },
    { label: "Moselle", code: "57" },
    { label: "Nièvre", code: "58" },
    { label: "Nord", code: "59" },
    { label: "Oise", code: "60" },
    { label: "Orne", code: "61" },
    { label: "Pas-de-Calais", code: "62" },
    { label: "Puy-de-Dôme", code: "63" },
    { label: "Pyrénées-Atlantiques", code: "64" },
    { label: "Hautes-Pyrénées", code: "65" },
    { label: "Pyrénées-Orientales", code: "66" },
    { label: "Bas-Rhin", code: "67" },
    { label: "Haut-Rhin", code: "68" },
    { label: "Rhône", code: "69" },
    { label: "Haute-Saône", code: "70" },
    { label: "Saône-et-Loire", code: "71" },
    { label: "Sarthe", code: "72" },
    { label: "Savoie", code: "73" },
    { label: "Haute-Savoie", code: "74" },
    { label: "Paris", code: "75" },
    { label: "Seine-Maritime", code: "76" },
    { label: "Seine-et-Marne", code: "77" },
    { label: "Yvelines", code: "78" },
    { label: "Deux-Sèvres", code: "79" },
    { label: "Somme", code: "80" },
    { label: "Tarn", code: "81" },
    { label: "Tarn-et-Garonne", code: "82" },
    { label: "Var", code: "83" },
    { label: "Vaucluse", code: "84" },
    { label: "Vendée", code: "85" },
    { label: "Vienne", code: "86" },
    { label: "Haute-Vienne", code: "87" },
    { label: "Vosges", code: "88" },
    { label: "Yonne", code: "89" },
    { label: "Territoire de Belfort", code: "90" },
    { label: "Essonne", code: "91" },
    { label: "Hauts-de-Seine", code: "92" },
    { label: "Seine-Saint-Denis", code: "93" },
    { label: "Val-de-Marne", code: "94" },
    { label: "Val-d’Oise", code: "95" },
    { label: "Guadeloupe", code: "971" },
    { label: "Martinique", code: "972" },
    { label: "Guyane", code: "973" },
    { label: "La Réunion", code: "974" },
    { label: "Mayotte", code: "976" }
]

const regions = [
    { label: "Alsace" },
    { label: "Aquitaine" },
    { label: "Auvergne" },
    { label: "Basse-Normandie" },
    { label: "Bourgogne" },
    { label: "Bretagne" },
    { label: "Centre" },
    { label: "Champagne-Ardenne" },
    { label: "Corse" },
    { label: "Franche-Comté" },
    { label: "Haute-Normandie" },
    { label: "Île-de-France" },
    { label: "Languedoc-Roussillon" },
    { label: "Limousin" },
    { label: "Lorraine" },
    { label: "Midi-Pyrénées" },
    { label: "Nord-Pas-de-Calais" },
    { label: "Pays de la Loire" },
    { label: "Picardie" },
    { label: "Poitou-Charentes" },
    { label: "Provence-Alpes-Côte d'Azur" },
    { label: "Rhône-Alpes" },
    { label: "Guadeloupe" },
    { label: "Martinique" },
    { label: "Guyane" },
    { label: "La Réunion" },
    { label: "Mayotte" }
]